name: HEYBUYMYSHIT.COM
description: 2003-2019 concert merchandise for sale
author: 09blk.com
exclude: [ _design, README ]
baseurl: "/"

pagination:
  enabled: true
  per_page: 16
  sort_reverse: false
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0

  trail: 
    before: 2
    after: 2

  extension: html
  indexpage: 'index'

