name: setlust.com
description: personal setlist collection of j. pirro
author: jonathan pirro
exclude: [ _design, README ]
baseurl: "/"

pagination:
  enabled: true
  per_page: 15
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0

  trail: 
    before: 2
    after: 2

  extension: html
  indexpage: 'index'

